/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author Lueng
 */

import java.awt.*;
import java.io.*;
import javax.swing.*;

import Lib.User.Userhistory;
import Lib.OrderProcessor.Cart;
import Lib.ShipmentDecorator.*;
import Lib.ShipmentFactory.*;

public class App extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(App.class.getName());

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
        loadProducts("lib/OrderProcessor/products.csv");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
   private void initComponents() {

        deliveryType = new javax.swing.ButtonGroup();
        decorator = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        payBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        expressDelivery = new javax.swing.JRadioButton();
        standardDelivery = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        insurance = new javax.swing.JCheckBox();
        giftWrap = new javax.swing.JCheckBox();
        totalcost = new javax.swing.JLabel();
        cost = new javax.swing.JLabel();
        shipmentCost = new javax.swing.JLabel();
        delivery = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        CartList = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        purchaseBtn = new javax.swing.JButton();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bookList = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel15.setFont(new java.awt.Font("TH Niramit AS", 1, 48)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("CART");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        payBtn.setFont(new java.awt.Font("TH Niramit AS", 1, 18)); // NOI18N
        payBtn.setText("PAY");
        payBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                payBtnActionPerformed(evt);
            }
        });
        purchaseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                purchaseBtnActionPerformed(evt);
            }
        });
        jLabel14.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Total Cost");

        jLabel16.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("SUMMARY");

        jLabel17.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Bath");

        jLabel18.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Shipment");

        jLabel19.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("Delivery");

        jLabel20.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Cost");

        jLabel21.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Bath");

        jLabel22.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Bath");

        jLabel23.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Bath");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        deliveryType.add(expressDelivery);
        expressDelivery.setText("Express Delivery");
        expressDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expressDeliveryActionPerformed(evt);
            }
        });

        deliveryType.add(standardDelivery);
        standardDelivery.setText("Standard Delivery");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(standardDelivery, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
            .addComponent(expressDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(expressDelivery)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(standardDelivery))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        insurance.setText("Insurance");

        giftWrap.setText("Gift Wrap");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giftWrap)
                    .addComponent(insurance))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(giftWrap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(insurance))
        );

        totalcost.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        totalcost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalcost.setText("0");

        cost.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        cost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cost.setText("0");

        shipmentCost.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        shipmentCost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        shipmentCost.setText("0");

        delivery.setFont(new java.awt.Font("TH Niramit AS", 1, 24)); // NOI18N
        delivery.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        delivery.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(cost, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel17))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(delivery, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21))))
                    .addComponent(payBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(shipmentCost, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalcost, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(cost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22)
                    .addComponent(shipmentCost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(delivery))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel23)
                    .addComponent(totalcost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(payBtn)
                .addGap(18, 18, 18))
        );

        CartList.setLayout(new java.awt.GridLayout(20, 0, 2, 10));
        jScrollPane3.setViewportView(CartList);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        kGradientPanel1.setkEndColor(new java.awt.Color(102, 51, 255));
        kGradientPanel1.setkStartColor(new java.awt.Color(102, 0, 153));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("HAYHA BOOK STORE");

        jTextField1.setText("Search");

        jButton9.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("X");
        jButton9.setBorder(null);
        jButton9.setContentAreaFilled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        purchaseBtn.setText("Purchase History");
        purchaseBtn.setToolTipText("");

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(717, 717, 717)
                        .addComponent(jButton9))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(purchaseBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(purchaseBtn)))))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton9)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        kGradientPanel2.setkEndColor(new java.awt.Color(102, 51, 255));
        kGradientPanel2.setkStartColor(new java.awt.Color(102, 0, 153));

        javax.swing.GroupLayout kGradientPanel2Layout = new javax.swing.GroupLayout(kGradientPanel2);
        kGradientPanel2.setLayout(kGradientPanel2Layout);
        kGradientPanel2Layout.setHorizontalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        kGradientPanel2Layout.setVerticalGroup(
            kGradientPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout bookListLayout = new javax.swing.GroupLayout(bookList);
        bookList.setLayout(bookListLayout);
        bookListLayout.setHorizontalGroup(
            bookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 882, Short.MAX_VALUE)
        );
        bookListLayout.setVerticalGroup(
            bookListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 668, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(bookList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(kGradientPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void updateTotals() {
        /*
         * Calculate cart total automatically
         */
        double cartTotal = 0;

        for (Component comp : CartList.getComponents()) {
            if (comp instanceof JLabel label) {
                String text = label.getText(); // e.g. "BookName 250"
                String[] parts = text.split(" ");
                if (parts.length >= 2) {
                    try {
                        double price = Double.parseDouble(parts[parts.length - 1]);
                        cartTotal += price;
                    } catch (NumberFormatException e) {
                        System.out.println("Invalid price format: " + parts[parts.length - 1]);
                    }
                }
            }
        }

        // delivery type
        double deliveryFee = 0;
        ShipmentFactory factory = new ShipmentFactory();
        Shipment shipment = null;

        if (expressDelivery.isSelected()) {
            shipment = factory.creatShipment("EXPRESS");
        } else if (standardDelivery.isSelected()) {
            shipment = factory.creatShipment("STANDARD");
        }

        if (shipment != null) {
            if (giftWrap.isSelected()) shipment = new GiftWrapDecorator(shipment);
            if (insurance.isSelected()) shipment = new InsuranceDecorator(shipment);
            deliveryFee = shipment.getCost();
        }

        double total = cartTotal + deliveryFee;
        cost.setText(String.format("%.2f", cartTotal));
        delivery.setText(String.format("%.2f", deliveryFee));
        totalcost.setText(String.format("%.2f", total));
    }


    private void loadProducts(String csvFile) {
        bookList.setLayout(new GridLayout(0, 2, 20, 20));
        try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {
            String line;
            br.readLine(); // skip header

            while ((line = br.readLine()) != null) {
                String[] parts = line.split(",");
                String name = parts[0];
                String author = parts[1];
                String price = parts[2];
                String imagePath = parts[3];

                JPanel productPanel = createProductPanel(name, author, price, imagePath);
                bookList.add(productPanel);
            }

            bookList.revalidate();
            bookList.repaint();

        } catch (IOException e) {
            System.out.println(e);
        }
    }

    private JPanel createProductPanel(String name, String author, String price, String imagePath) {
        JPanel panel = new JPanel();
        panel.setPreferredSize(new Dimension(400, 250));
        panel.setBackground(new Color(204, 204, 204));
        panel.setBorder(BorderFactory.createEtchedBorder());
        panel.setLayout(null);

        ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
        Image scaled = icon.getImage().getScaledInstance(190, 230, Image.SCALE_SMOOTH);
        JLabel pic = new JLabel(new ImageIcon(scaled));
        pic.setBounds(10, 10, 190, 230);

        JLabel lblName = new JLabel("Name: " + name);
        lblName.setBounds(205, 10, 180, 25);

        JLabel lblAuthor = new JLabel("Author: " + author);
        lblAuthor.setBounds(205, 40, 180, 25);

        JLabel lblPrice = new JLabel("Price: " + price);
        lblPrice.setBounds(205, 70, 180, 25);

        JButton btnAdd = new JButton("ADD TO CART");
        btnAdd.setBounds(205, 200, 210, 30);

        btnAdd.addActionListener(e -> {
            JLabel cartLabel = new JLabel(name + " " + price);
            CartList.add(cartLabel);
            CartList.revalidate();
            CartList.repaint();
            updateTotals(); 
        });


        panel.add(pic);
        panel.add(lblName);
        panel.add(lblAuthor);
        panel.add(lblPrice);
        panel.add(btnAdd);

        return panel;
    }


   private void payBtnActionPerformed(java.awt.event.ActionEvent evt) {
    // --- 1. Check cart is not empty ---
    if (CartList.getComponentCount() == 0) {
        showMessage("Please add items to the cart before payment.");
        return;
    }

    // --- 2. Calculate total price from cart items ---
    double cartTotal = 0;
    for (Component comp : CartList.getComponents()) {
        if (comp instanceof JLabel label) {
            String[] parts = label.getText().split(" ");
            if (parts.length >= 2) {
                try {
                    double price = Double.parseDouble(parts[parts.length - 1]);
                    cartTotal += price;
                } catch (NumberFormatException e) {
                    System.out.println("Invalid price: " + parts[parts.length - 1]);
                }
            }
        }
    }

    // --- 3. Create delivery type (base shipment) ---
    ShipmentFactory shipmentFactory = new ShipmentFactory();
    Shipment baseShipment = null;

    if (expressDelivery.isSelected()) {
        baseShipment = shipmentFactory.creatShipment("EXPRESS");
    } else if (standardDelivery.isSelected()) {
        baseShipment = shipmentFactory.creatShipment("STANDARD");
    } else {
        showMessage("Please select a delivery method.");
        return;
    }

    // --- 4. Apply decorators on top of the base shipment ---
    Shipment finalShipment = baseShipment;

    if (giftWrap.isSelected()) {
        finalShipment = new GiftWrapDecorator(finalShipment);
    }

    if (insurance.isSelected()) {
        finalShipment = new InsuranceDecorator(finalShipment);
    }

    // --- 5. Calculate costs separately ---
    double deliveryFee = baseShipment.getCost();   // pure delivery cost
    double addonFee = finalShipment.getCost() - baseShipment.getCost(); // only decorators
    double total = cartTotal + finalShipment.getCost();

    // --- 6. Display results ---
    cost.setText(String.format("%.2f", cartTotal));        // product total
    shipmentCost.setText(String.format("%.2f", addonFee)); // add-ons
    delivery.setText(String.format("%.2f", deliveryFee));  // delivery
    totalcost.setText(String.format("%.2f", total));       // grand total

    // --- 7. Success message ---
    showMessage("Pay successful!");
    showMessage("Purchase recorded to history.");
}


    private void showMessage(String msg) {
    JOptionPane.showMessageDialog(this, msg);
    }                                 

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
            dispose();
    }        

    private void giftWrapActionPerformed(java.awt.event.ActionEvent evt) {                                         
       if (evt.getSource() == "Gift Wrap") {
            Shipment giftwrapped = new GiftWrapDecorator(null);
        } else if(evt.getSource() == "Insurance") {
            Shipment Insurance = new InsuranceDecorator(null); // ต้อง setup สร้างคลาส Cart สำหรับเก็บข้อมูลหนังสือ
        }
    }              

    private void expressDeliveryActionPerformed(java.awt.event.ActionEvent evt) {                                                                                               
        ShipmentFactory shipmentFactory = new ShipmentFactory();
        if (evt.getSource() == "Standard Delivery") {
            Shipment StandardShipment = shipmentFactory.creatShipment("STANDARD");
            //StandardShipment.getCost();
        } else if (evt.getSource() == "Express Delivery") {
            Shipment ExpressShipment = shipmentFactory.creatShipment("EXPRESS");
            //ExpressShipment.getCost();
        }
    }     
    
    private void purchaseBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try (BufferedWriter bw = new BufferedWriter(new FileWriter("Lib/User/history.csv", true))) {
        for (Component comp : CartList.getComponents()) {
            if (comp instanceof JLabel label) {
                String text = label.getText(); // เช่น "Book Name 250"
                // แยกชื่อหนังสือกับราคา (ถ้ารูปแบบคงที่)
                String[] parts = text.split(" ");
    
                if (parts.length >= 2) {
                    String name = parts[0];

                    String price = parts[parts.length - 1]; // สมมุติว่าเป็นเลขราคา
                    for(int i=0;i<parts.length-1;i++){
                         bw.write(parts[i]+" ");
                    }
                    bw.write("," + price);
                    bw.newLine();
                }
            }
        }
    }   catch (IOException e) {
        System.out.println("Error writing history: " + e.getMessage());
    }
    new Userhistory().setVisible(true);
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new App().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel CartList;
    private javax.swing.JPanel bookList;
    private javax.swing.JLabel cost;
    private javax.swing.ButtonGroup decorator;
    private javax.swing.JLabel delivery;
    private javax.swing.ButtonGroup deliveryType;
    private javax.swing.JRadioButton expressDelivery;
    private javax.swing.JCheckBox giftWrap;
    private javax.swing.JCheckBox insurance;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private javax.swing.JButton payBtn;
    private javax.swing.JButton purchaseBtn;
    private javax.swing.JLabel shipmentCost;
    private javax.swing.JRadioButton standardDelivery;
    private javax.swing.JLabel totalcost;
    // End of variables declaration                     
}
